"""add cv groups and versions

Revision ID: 06134ba58686
Revises: 71497bcd6703
Create Date: 2026-04-25 20:18:23.311494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06134ba58686'
down_revision: Union[str, Sequence[str], None] = '71497bcd6703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_cv_groups_user_name')
    )
    op.create_index(op.f('ix_cv_groups_id'), 'cv_groups', ['id'], unique=False)
    op.create_index(op.f('ix_cv_groups_user_id'), 'cv_groups', ['user_id'], unique=False)
    op.create_table('cv_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('filename_original', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cv_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'version_number', name='uq_cv_versions_group_version')
    )
    op.create_index(op.f('ix_cv_versions_group_id'), 'cv_versions', ['group_id'], unique=False)
    op.create_index(op.f('ix_cv_versions_id'), 'cv_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_versions_id'), table_name='cv_versions')
    op.drop_index(op.f('ix_cv_versions_group_id'), table_name='cv_versions')
    op.drop_table('cv_versions')
    op.drop_index(op.f('ix_cv_groups_user_id'), table_name='cv_groups')
    op.drop_index(op.f('ix_cv_groups_id'), table_name='cv_groups')
    op.drop_table('cv_groups')
    # ### end Alembic commands ###
